### PR TITLE
Initial Crypto SDK (utilities)

### PR DESCRIPTION
**Pull request by lbeder**
This PR include the initial setup of our cross-platform `crypto-sdk` C++ library with utilities to support account generate (WIP, since some specs are pending):

1. Complete `cmake` setup to build both the `crypto-sdk` library and its tests (support for both release and debug builds). Prerequisites are defined as `ExternalProject` with either specific git tag clone and verification (`gtest`) or download from URL with SHA256 verification (`libgpg_error`, and `libgcrypt`.
2. Hashing: SHA256, SHA512, RIPEMD160 (required for Ripple-like address scheme).
3. Checksum: CRC32 (required for Orbs address scheme).
4. Encoding: BASE58 (required for Ripple-like address scheme).
5. Full test suite (utilizing Google Test [`gtest`] and Google Mock [`gmock`] libraries.

TBD (in future PRs):
- Integrate into build system and CI (both build and tests).
- Secure "account" creation.
- Transaction signing.
- Transaction broadcast.
- Transaction receipt/status.

### CODE REVIEW

**Comment by idandash** [comment]
@lbeder please add the library's interface, and what each of the implementations is based on (external lib or developed from scratch, and also whether it follows a standard specification [RFC and so on] )

**Comment by lbeder** [comment]
@idandash the README.md was updated

**Comment by lbeder** [comment]
@netoneko thanks for the Dockerfile! It uncovered some build contamination issues.

**Comment by lbeder** [comment]
@idandash I'll gladly address your feedback in a future PRs.

**Pull request merged**
