### PR TITLE
Automatically deploy master to staging environment

### PR DESCRIPTION
**Pull request by netoneko**

### CODE REVIEW

**Comment by lbeder** [comment]
@netoneko can you why is it stuck on `ci/circleci`?

**Comment by netoneko** [comment]
@lbeder I suppose because it waits for the second part of the build which is `deploy`, but circle ci skips it because the branch is not `master`.

Maybe it will go away if I try updating the branch.

**Comment by netoneko** [comment]
@lbeder you have to check a single box for `build` in Github settings, please refer to Circle CI docs: https://circleci.com/docs/2.0/workflows-waiting-status/

**Comment by lbeder** [comment]
@netoneko this is what we have now: 

screen shot 2018-02-13 at 0 22 01

I'll change it to `ci/circle: build` instead.

**Pull request merged**
