### PR TITLE
Sidechain Service - Parametrized options + minor styling fix

### PR DESCRIPTION
**Pull request by idandash**

### CODE REVIEW

**Comment by lbeder** [comment]
@netoneko could you check why this build fails (unrelated to the PR)?

**Comment by netoneko** [comment]
@lbeder sure

**Comment by idandash** [comment]
@lbeder why did you close it?

**Comment by lbeder** [comment]
I've merged it and then closed it. Why?

**Comment by idandash** [comment]
You haven't merged it yet. Please do.

**Comment by lbeder** [comment]
Shit, I thought that I did. I've waited for @netoneko to fix the build script and forgot about it.

**Pull request merged**
