### PR TITLE
Initial support for AWS ECS

### PR DESCRIPTION
**Pull request by netoneko**
Run `orbs-network` container on ECS.

Next step would be scaling and discovery in a common network with ability to scale up and down.

### CODE REVIEW

**Comment by idandash** [comment]
@netoneko AWS account-specific settings should not be hard-coded

**Comment by netoneko** [comment]
@idandash fixed.

**Comment by lbeder** [comment]
@netoneko do you feel that this PR is good to go?

**Comment by netoneko** [comment]
@lbeder yes. It paves the road to next steps of running our infrastructure both locally and in the cloud.

**Pull request merged**
